requirements.txt
Addresses #133 
Changing `requirements.txt` to install package from online instead of from a local tarball.
=> Modify requirements to install Dash Bio from TestPyPI.

dash_bio/AlignmentChart.py, dash_bio/AlignmentViewer.py, dash_bio/Circos.py, dash_bio/Ideogram.py, dash_bio/Molecule3dViewer.py, dash_bio/NeedlePlot.py, dash_bio/OncoPrint.py, dash_bio/SequenceViewer.py, dash_bio/Speck.py, dash_bio/metadata.json, dash_bio/package.json, src/lib/components/NeedlePlot.react.js
=> Remove events

CONTRIBUTING.md
Just noticed this, real quick!
=> Fix path to demo apps

assets/general-app-page.css, tests/dashbio_demos/utils/app_wrapper.py
Make topbar shorter, add button to go to GitHub code, and change fonts.
Closes #166 
Some minor visual changes.
=> Fix topbar design.

assets/speck-style.css, tests/dashbio_demos/app_speck.py, tests/dashbio_demos/utils/app_standalone.py
Add more controls to the application and fix the location of the assets folder (which was not loading properly).
=> Speck app improvements

CONTRIBUTING.md
Specify more steps for changing the Procfile and config.py before deployment of standalone apps.
=> Add updates to CONTRIBUTING.md.

CHANGELOG.md, dash_bio/package.json, package.json, requirements.txt
Update the version (published on TestPyPi) to `0.0.5`.
=> Update version number to reflect changes to filenames in .

.github/before_merging.md
Hello,
Following our discussion around 2c7fa7db66ac6c26f712c8ad44a059a3a27afc6f, let's make it explicit that the merge pull requests into master the default way.
=> Specify how to merge pull request

.circleci/config.yml, tests/requirements.txt, tests/test_common_features.py, tests/test_manhattan_plot.py, tests/test_skeleton.py, tests/test_usage.py, tests/test_volcano_plot.py
Closes #180 
Change `tests/requirements.txt`
Fix deprecated references to `pytest_dash.utils`
=> Update pytest-dash to v2.0.0

CONTRIBUTING.md, tests/test_skeleton.py
The two commits are unrelated, but they are tiny.
The first one follows from #187.
=> Update docs and boilerplate (minor changes)

requirements.txt, tests/dashbio_demos/app_molecule3d.py
Closes #161 
Change typo in call to styles parser function.
=> Fix rendering issue.

tests/dashbio_demos/app_clustergram.py
Closes #160. 
Remove error message generated when data have been changed successfully, but have not been fully loaded yet.
=> Add loading message upon data change.

CHANGELOG.md, dash_bio/Ideogram.py, dash_bio/metadata.json, dash_bio/package.json, package.json
Add changes to Ideogram props and to setup install requirements.
=> Update version to 0.0.6.

src/lib/components/Circos.react.js
Closes #205 
Replace unicode right arrow with a greater-than sign.
=> Remove unicode string.

assets/mol3d-style.css, tests/dashbio_demos/app_molecule3d.py
Make changes to the coloring of the Molecule3D app.
=> Update description and colors.

CHANGELOG.md, dash_bio/package.json, package.json, requirements.txt, src/lib/components/OncoPrint.react.js, tests/requirements.txt
Closes #215 
Remove references to Dash events, regenerate bundle, and release `0.0.8-rc4` on PyPI.
=> Oncoprint remove events

dash_bio/package.json, package-lock.json, package.json, tests/test_ideogram.py
Closes #203 
Locked the version of ideogram to v1.4.1
=> Fix ideogram rotation

CHANGELOG.md, dash_bio/component_factory/_clustergram.py, dash_bio/package.json, package-lock.json, package.json, requirements.txt, setup.py, tests/dashbio_demos/app_clustergram.py, tests/requirements.txt
Closes #74  
The clustergram component actually had quite a lot of things wrong with it: 
* it was using a soon-to-be-deprecated imputer function
* it was not rearranging the rows and columns on the heatmap when there was clustering (surprised nobody caught this until now!) 
* it was losing all data about labels if there was no clustering on that dimension. (e.g., if it was clustered by "row" and the user tried to display column labels, they would simply be empty)
On top of that, the app was also changed to prevent the user from not specifying any dimensions along which to compute clustering.
=> Clustergram component improvements

dash_bio/component_factory/_clustergram.py, dash_bio/component_factory/_manhattan.py, dash_bio/component_factory/_volcano.py, dash_bio/package.json, package.json, requirements.txt, tests/requirements.txt
Closes #233 
Updating docstrings to be parseable by Sphinx (see related issue for more specific formatting).
=> Reformat docstrings

dash_bio/package.json, package-lock.json, package.json, requirements.txt
Closes #248 
Publish new rc version of Dash Bio package (`0.0.8-rc13`) to TestPyPI, update all auto-generated files accordingly, and bump version in the requirements file. This new rc version includes the bundle with the Speck fix implemented in #171.
=> Speck bundle fix

tests/dashbio_demos/app_speck.py
Closes #251
Change "About" tab to follow the pattern of the other redesigned apps, with a header "What is ..." and a longer description of the component/app.
=> Add text for 'About' tab.

dash_bio/Ideogram.py, dash_bio/metadata.json, src/lib/components/Ideogram.react.js
Closes #235 
I'm improving the Ideogram component (docstrings, won't show in UI).
@shammamah I'm not sure this change is worth an entry in the CHANGELOG and, hence, bumping the package version. But, if you think so, I'll happily do it.
Running `npm run build:all` resulted in updates to `Ideogram.py` and `metadata.json` but not to `bundle.js` -- is it the expected behaviour?
=> Improve description of Ideogram component.

assets/manhattanplot-style.css, tests/dashbio_demos/app_manhattan_plot.py
Closes #224 
* change colors 
* move controls to a `dcc.Tabs` component that is on the left side of the component
=> Begin ManhattanPlot app redesign.

renovate.json
As per https://github.com/plotly/dash-bio/pull/262#issuecomment-475251845
=> Exclude React from Renovate updates.

renovate.json
Closes #264 
Fixes #269 
I hadn't noticed the *Important* note at https://renovatebot.com/docs/configuration-options/#excludepackagenames
See also: https://renovatebot.com/docs/configuration-options/#ignoredeps
=> Define a list of package names for Renovate to ignore.

renovate.json
Closes #264 
* Oops
* Thanks @Marc-Andre-Rivet :)
* Don't always trust the Renovate Bot ;)
=> Fix duplicated key packageRules in Renovate config

tests/dashbio_demos/app_needle_plot.py
=> Clarify description of fields for protein domain data (JSON files).

dash_bio/package.json, package.json, requirements.txt
Releasing a new official version of Dash Bio package. 
See CHANGELOG.
=> 0.0.8 release

assets/general-app-page.css, assets/needleplot-style.css, assets/sequence-viewer-style.css, tests/dashbio_demos/app_sequence_viewer.py
This just adds a stylesheet that holds the common elements used in the apps. The intent of this PR is to remove repetition for the other apps. Sequence viewer has been styled with this new stylesheet as an example. The other apps can be styled in a subsequent PR.
=> Common stylesheet

CHANGELOG.md, dash_bio/component_factory/_clustergram.py, dash_bio/package.json, package.json
Closes #307 
* Add default values for row and column labels, since this parameter is specified as optional.
=> Clustergram default values

CHANGELOG.md, dash_bio/Molecule3dViewer.py, dash_bio/metadata.json, dash_bio/package.json, package.json, requirements.txt, src/lib/components/Molecule3dViewer.js, tests/dashbio_demos/app_molecule3d.py
Closes #306 
* Fix the `propTypes` specification for `styles`. 
* Change the accepted props for `selectionType` to all-lowercase (e.g., `atom` instead of `Atom`) to be more cohesive with other Dash Bio and Dash prop values.
=> Mol3d component improvement

.github/pull_request_template.md
I'm just feeling annoyed by these extra blank lines... :)
=> Delete trailing blank lines.

CHANGELOG.md, dash_bio/package.json, dash_bio/utils/xyz_reader.py, package.json, requirements.txt
Closes #342 
* Add support for whitespaces at beginning and end of line for XYZ file parser.
=> Improve xyz reader

assets/alignmentchart-style.css, assets/general-app-page.css, tests/dashbio_demos/app_alignment_viewer.py, tests/dashbio_demos/app_circos.py, tests/dashbio_demos/app_clustergram.py, tests/dashbio_demos/app_ideogram.py, tests/dashbio_demos/app_manhattan_plot.py, tests/dashbio_demos/app_molecule3d.py, tests/dashbio_demos/app_needle_plot.py, tests/dashbio_demos/app_onco_print.py, tests/dashbio_demos/app_sequence_viewer.py, tests/dashbio_demos/app_speck.py, tests/dashbio_demos/app_volcano_plot.py
Closes #213 
* Wrap each Dash Bio component in a `dcc.Loading` component to improve UX.
=> Add loading states to all apps.

dash_bio/Circos.py, dash_bio/Molecule3dViewer.py, dash_bio/NeedlePlot.py, dash_bio/Speck.py, dash_bio/metadata.json, src/lib/components/Circos.react.js, src/lib/components/Molecule3dViewer.js, src/lib/components/NeedlePlot.react.js, src/lib/components/Speck.react.js
=> Add docstrings

CHANGELOG.md, dash_bio/package-info.json, package-lock.json, package.json, requirements.txt
New minor version of the package.
* Version number update
=> 0.1.1 release

CHANGELOG.md, dash_bio/package-info.json, package-lock.json, package.json, requirements.txt
Closes #372 
Now, triple bonds can be viewed:
* Change https://github.com/plotly/molecule-2d-for-react so that triple bonds display correctly.
=> Mol2d triple bonds fix

dash_bio/package-info.json, package-lock.json, package.json, requirements.txt, tests/test_onco_print.py
Closes #391  
* Changed selector for legend items in Onco Print test from `.legendbar` (in plotly.js 1.47.x) to `g.traces` (in plotly.js 1.48.x).
=> Fix Onco Print test error upon running `npm audit fix`

CHANGELOG.md, dash_bio/Circos.py, dash_bio/Ideogram.py, dash_bio/component_factory/_clustergram.py, dash_bio/package-info.json, package.json, requirements.txt, tests/dashbio_demos/app_clustergram.py
=> Improve naming in Clustergram.

.circleci/config.yml, tests/dashbio_demos/deployment/app_remotes.txt, tests/dashbio_demos/deployment/generate_procfile.py
Closes #403 
* Added a CircleCI job that automatically deploys the `master` branch and adds Google Analytics code at the time of deployment. This is fine to do, since we have a precondition on any changes being merged into `master` (namely, that
=> Add GA code and auto-deployments.

CONTRIBUTING.md, README.md
Closes #405 
- In the README and CONTRIBUTING docs: 
- Change all mentions of `dash-bio.plotly.host` to point to `dash-gallery.plotly.host`
- Fix names for Mol3D component (changed from MolJS) 
- Add Mol2D 
- Alphabetize component names within categories
=> Update gallery links

.circleci/config.yml
=> Remove unneeded quotes from YAML.

.buildpacks
=> fix: use updated buildpack

.github/pull_request_template.md
Closes #464 
* Remove outdated "before merging" steps 
* Move "closing an issue" option to top
=> Update PR template.

.circleci/config.yml, tests/dashbio_demos/common/layout_helper.py
Closes #483 
* Fixed the "View on GitHub" links
=> Fix URL to source code.

dash_bio/__init__.py
Followup to https://github.com/plotly/dash/pull/1493
=> fix dash import test

dash_bio/component_factory/_volcano.py
Can't see plot in dark mode. Changed the default dot color to blue.
=> Changed default scatter color

.github/combine-prs.yml, renovate.json
Adds a combine-pr's Github workflow to combine dependabot PR's which are ready to merge.  Also disables renovatebot until it is removed from the repo.
=> Adding combine-prs workflow

CHANGELOG.md, dash_bio/component_factory/_clustergram.py, tests/integration/test_clustergram.py
Closes #447
Add row and column colors
=> Add row and column colors
