.pylintrc, index.py, requirements.txt, tests/dashbio_demos/app_alignment_viewer.py, tests/dashbio_demos/app_circos.py, tests/dashbio_demos/app_clustergram.py, tests/dashbio_demos/app_ideogram.py, tests/dashbio_demos/app_manhattan_plot.py, tests/dashbio_demos/app_molecule3d.py, tests/dashbio_demos/app_needle_plot.py, tests/dashbio_demos/app_oncoprint.py, tests/dashbio_demos/app_sequence_viewer.py, tests/dashbio_demos/app_speck.py, tests/dashbio_demos/app_volcano_plot.py, tests/dashbio_demos/utils/app_standalone.py, tests/dashbio_demos/utils/app_wrapper.py, tests/requirements.txt
Lays the ground for #133.
With this PR, it is still possible to run `python index.py` from the root of the repo, but now also possible to run `python tests/dashbio_demos/app_ideogram.py`.
What's left to do:
=> Let example/demo apps run as standalone apps.

tests/dashbio_demos/utils/app_wrapper.py
Instead of directing to the same page (as is the case currently), the logo should serve as a "back" button.
=> Make logo link back to portal.

tests/dashbio_demos/utils/app_wrapper.py
Change the Dash Bio logo at the top to refresh the page (with `html.A`) instead of the current `dcc.Link`, which doesn't reload the page when the location is changed.
=> Redirect to portal htmla

tests/test_common_features.py
If a prop is a dict which contains "subprops", in order to test those one has to use a callback on the prop with a dict containing the subprop's key and value one would like to test. This testing can be made generic
if there are default values defined in the `defaultProps` of the .react.js file, they are not accessible through `dash.dependencies.Input` or `dash.dependencies.State` 
```
COMPONENT.propTypes = {
givenProp: PropTypes.shape({
subprop1: PropTypes.string,
subprop2: PropTypes.int,
})
};
COMPONENT.defaultProps = {
givenProp: {
subprop1: "a string",
subprop2: 12
}
};
```
If one define a callback like this one
```
@app.callback(
Output(), # not relevant for the example
[Input()], # not relevant fot the example
[State('COMPONENT', 'givenProp')]
):
def do_something(_, prop):
```
This …
=> Add generic test for the subprops

.circleci/config.yml
Hello,
I thought we could add this command (that I personally run locally) to spare the following warnings on Circle CI:
=> Upgrade pip before installing requirements

CONTRIBUTING.md
Addresses #175
Specify that upper camel case should be used to name React and Python components.
=> Add naming conventions.

tests/test_skeleton.py
As per our February 19 discussion, we might as well order arguments of the `assert_callback()` function as nclicks, prop name, ... to match the order suggested in the `COMPONENTNAME_props_callback()` function, declared before.
This change is not functional, since this code never runs. It's just easier on the brain to read "nclicks, prop name, ..." and then again "nclicks, prop name, ..." (rather than "prop name, niclicks, ..." on the second time).
=> Reorder function arguments in boilerplate code.

tests/test_ideogram.py
Fix to prevent the ideogram tests to fail due to time loading the components
Add explicit waiting time for now so the test pass
=> Add explicit wait time before assessing existence of elements in tests

assets/sequence-viewer-style.css, tests/dashbio_demos/app_sequence_viewer.py
Sequence viewer app redesign. 
* Move all controls to `dcc.Tabs` 
* Move sequence info underneath sequence viewer component and group the two in a single parent div 
* Fix heights of both sequence info container and sequence viewer component container
* Change accent colour
=> Sequenceviewer redesign

renovate.json
Closes #240 
We are grouping the automated dependency updates into a single PR (from the Renovate Bot).
So from tomorrow onwards, we can review them all at once.
Reference: https://renovatebot.com/docs/presets-group/
=> Add preset group:all to Renovate config.

renovate.json
This is about dependency management. Taking care of one thing at a time... as per https://github.com/plotly/dash-bio/pull/262#issuecomment-475241271
See PR title.
Reference: https://renovatebot.com/docs/configuration-options/#excludepackagenames
=> Exclude ideogram from Renovate updates.

.circleci/config.yml, renovate.json
Addresses https://github.com/plotly/dash-bio/pull/272#issuecomment-475899788.
Reference: https://renovatebot.com/docs/configuration-options/#excludepackagepatterns
=> Exclude react-* packages from Renovate updates

requirements.txt, src/lib/components/Ideogram.react.js, tests/test_ideogram.py
Adresses #260. 
Certain integration tests count (expected) elements by having Selenium find them (CSS selector). Sometimes, the underlying function times out before updated elements could be found and, hence, counted. 
Delving into the Ideogram tests, I have standardized the finding / counting of elements. I have pushed frequently to have 'statistics' on CI test failures, and lately they haven't failed... So I'm thinking of not changing 
```
-    chromosomes = wait_for_elements_by_css_selector(driver, '.chromosome')
+    chromosomes = wait_for_elements_by_css_selector(driver, '.chromosome', timeout=20.0)
```
(at least, not yet).
=> Update ideogram tests.

renovate.json
In light of #281, I wasn't able to use `excludePackagePatterns` in the Renovate config.
So I'm suggesting a small change, which has worked so far in terms of ignoring updates for React and Ideogram. Thanks @Marc-Andre-Rivet for bearing with all my questions!
=> Tell Renovate to ignore react deps explicitly.

CHANGELOG.md, dash_bio/AlignmentChart.py, dash_bio/AlignmentViewer.py, dash_bio/Circos.py, dash_bio/Ideogram.py, dash_bio/Molecule3dViewer.py, dash_bio/NeedlePlot.py, dash_bio/OncoPrint.py, dash_bio/SequenceViewer.py, dash_bio/Speck.py, requirements.txt, setup.py, tests/dashbio_demos/app_alignment_viewer.py, tests/dashbio_demos/app_circos.py, tests/dashbio_demos/app_clustergram.py, tests/dashbio_demos/app_ideogram.py, tests/dashbio_demos/app_manhattan_plot.py, tests/dashbio_demos/app_molecule3d.py, tests/dashbio_demos/app_needle_plot.py, tests/dashbio_demos/app_sequence_viewer.py, tests/dashbio_demos/app_speck.py, tests/dashbio_demos/sample_data/needle_mutations_data.json
(note that I am not publishing a new version of the package, since the problem with Speck's `view` prop from #241 still needs to be fixed)
Updates to `dash` and `dash-renderer` ensure that `setProps` does not have to be defined by creating a callback that takes the component as input. This fixes part of the issue referenced in #241. 
* Change the Dash version in the requirements for the demo apps and in the setup install requirements for Dash Bio. 
* Change the demo apps to have default tabs, as the newest version of `dash-core-components` does not display the contents of the first tab by default.
* Make the IDs for the tabs in each of the demo apps more uniform. 
* Remove unnecessary callback in Speck application.
=> Dash renderer update

package-lock.json
This should have been part of #298 (diff came up as I ran `npm i`).
=> Catch up 0.0.8 release

CHANGELOG.md, assets/clustergram-style.css, dash_bio/component_factory/_clustergram.py, dash_bio/package.json, package-lock.json, package.json, requirements.txt, tests/dashbio_demos/app_clustergram.py
Addresses part of #288 
* Add ability in the Clustergram component to produce a dictionary that can translate the `clickData` from `dcc.Graph` into the cluster that was clicked.
* Add options to return the above dictionary, as well as an option to use precomputed traces, into the Clustergram component. Both of these are false by default. 
* Return *only* the figure data by default. This avoids the need to unpack values if one only wishes to display the clustergram.
* Add date to CHANGELOG for version `0.0.8`. 
* Refine and make use of the option to use precomputed traces in the demo application.
=> Clustergram improvements

dash_bio/package.json, package.json, requirements.txt, src/lib/components/Speck.react.js
Closes #310 
This issue was due to the fact that `loadStructure` was not being called from `componentDidMount`, and instead only from `componentDidUpdate`. I also ran into an issue where `loadStructure` failed because  `this.state.renderer` was still `null`, even after having defined it -- this was because `setState` does not immediately mutate the state of the component (https://reactjs.org/docs/react-component.html#setstate). From the documentation: 
>`setState()` does not always immediately update the component. It may batch or defer the update until later. This makes reading `this.state` right after calling `setState()` a potential pitfall. Instead, use `componentDidUpdate` or a `setState` callback (`setState(updater, callback)`), either of which are guaranteed to fire after the …
=> Speck component rendering fix

CHANGELOG.md, Procfile, config.py, dash_bio/package.json, package.json, requirements.txt, src/lib/components/Speck.react.js
Previously, the Speck component was trying to calculate the radius for an atom even if no atoms were present in the system. This led to an exception and a failure to render. 
Now, the function `loadStructure` simply returns if there are no atoms supplied in the system and consequently avoids this error.
I also fixed the CHANGELOG to have nicer formatting and added the fix from #311 to the notes for the 0.0.9 release.
=> Speck system fix

.circleci/config.yml, requirements.txt
Closes #300. 
We wanted to ensure that `dash_bio/bundle.js` builds successfully. This is now done, with the changes submitted here.
I've added command `npm run build:js` to the "node" job, which runs in a node.js environment.
Ultimately, we may want to address the following warning:
=> Build actual dash_bio node.js package in CI build.

dash_bio/package.json, package-lock.json, package.json, requirements.txt
Closes #313 
* I transferred ownership of all of the forked repos that were under my account to Plotly, and changed the dependency locations to reflect that. 
* In the `molecule-3d-for-react` fork I made, I addressed https://github.com/Autodesk/molecule-3d-for-react/issues/36 and it no longer gives us the error I was getting.
=> Updated dependencies and PropTypes fix

tests/dashbio_demos/app_manhattan_plot.py
Addresses part of #289 
Trim down the dataset to use only the first 100 rows of the data for each chromosome in order to speed up load/response times for the graph.
=> Trim down data before plotting.

requirements.txt
Deployment to DDS fails because the version of `pandas` is not specified. If there is already a version of `pandas` installed in the container, it will not update (because `pip` will recognize the package as already having been installed). We didn't run into this problem with the demo apps because the heroku containers are ephemeral and consequently will always have the latest version of `pandas`.
=> Specify pandas version in requirements.

README.md
This API token is unnecessary, now that the project is public.
This is a minor change.
=> Remove API token from CI status badge.

requirements.txt
Closes #332 
With this change, we shouldn't run into any more surprises when deployment with DDS. That being said, I don't understand why the current version of Dash would be `>=0.40.0` (https://github.com/plotly/dash-bio/blame/master/requirements.txt didn't enlighten me): I 'reverted' `dash>=0.40.0` to `dash==0.40.0` because, if I remember correctly, we need to upgrade React to v16 before we can upgrade our Dash dependency.
I have used package versions from my local dev environment (output of `pip freeze`).
=> Take snapshot of Python environment

CHANGELOG.md, dash_bio/package.json, package.json, requirements.txt, setup.py
=> Update homepage on PyPI.

CHANGELOG.md, dash_bio/package-info.json, package.json, requirements.txt
The most major change in this version is that the JS distribution is now published on NPM.
=> 0.0.11 release

tests/test_ideogram.py
The `selenium` utility https://github.com/plotly/pytest-dash/blob/d0291909b1230f3c39473b6f038ae7a6b48670c3/pytest_dash/wait_for.py#L44 often fails to find the elements identified in some of our tests (specifically in file `tests/test_ideogram.py`) within the default timeout. Values we test for are therefore not updated, leading to CI build failures (we then relaunch CI builds manually).
This changeset won't change the world, but it could spare us a few CI fails (iirc, last time I toyed with this, I ended up not submitting the change because I wasn't able to observe these timeout-related fails locally). Also, note that this change will be subject to the upcoming refactoring of `pytest-dash` by @byronz.
=> Double timeout for Ideogram tests which fail often.

requirements.txt, setup.py
I was about to start a WIP branch where I would use `dash-bio-utils==0.0.3rc1`. Since version `0.0.2` is available, we might as well use it; meanwhile I fixed a couple other things.
=> Clean up dependency declarations.

dash_bio/package-info.json, package-lock.json, package.json
* Changed dependency for molecule-2d-for-react to the Plotly fork, which uses external `prop-types`.
=> Mol2d proptypes fix

CHANGELOG.md, dash_bio/metadata.json, dash_bio/package-info.json, package.json, requirements.txt, src/lib/components/Molecule3dViewer.js
Closes #376 
* Added default props for Molecule3dViewer: `selectionType`, `backgroundColor`, and `backgroundOpacity`. 
* Handled case in which `selectionType` is null (this was previously causing an error if the prop had an undefined value, since it assumes that the prop is a string.
=> Mol3d default props

CHANGELOG.md, dash_bio/package-info.json, package-lock.json, package.json, requirements.txt
Removed the CHANGELOG entries related to the version of `dash_bio_utils` (not related to the actual library, but related to the demo apps) and moving the package location for Circos (irrelevant to the functionality of the package).
=> 0.1.2 release

.circleci/config.yml, dash_bio/Circos.py, dash_bio/Ideogram.py, dash_bio/package-info.json, package.json, requirements.txt, setup.py, tests/requirements.txt
Closes https://github.com/plotly/dash-docs/issues/598
Right now, Dash Bio is incompatible with newer versions of Dash including that which we use in documentation. Ideally, component libraries have a loose dependency on Dash - the user should be able to upgrade and install Dash independently of the component package, and the component package shouldn't have to create a new release with every release of Dash.
=> Allow any version of Dash

requirements.txt
Let's use the newly released version of `dash-bio-utils`.
`dash-bio` will now use https://github.com/plotly/dash-bio-utils/releases/tag/v0.0.4.
=> Update dash-bio-utils to just released version.

.circleci/config.yml, CONTRIBUTING.md
Updated to (hopefully) prevent the version issues we ran into on #444, as well as to ensure that `postbuild` runs.
=> Update CircleCI jobs and contributing guidelines

.circleci/config.yml
Closes #462.
~I was quite tempted to add a Python command right next to `python unit_test_data_setup.py`. Instead, should we separate Python unit tests and JS unit tests into two different steps?~
Oops, that step of running Python unit tests definitely can't be part of a `node` job! I have rebased.
=> Let CI run Python unit tests

.circleci/config.yml
The path to the modified apps for dash-gallery deploys was incorrect, so this change fixes that.
=> fix: use correct path for apps modified

deploy
Some of the apps had pre-existing history, which ended up being merged - and not overwritten - with the new app history. This change was pulled from dash-sample-apps, where I saw this exact issue last week.
=> fix: correct case where pre-existing history conflicts with new changes

deploy
This ensures we have the common layout_helper file in all apps.
=> fix: add missing layout_helper file

tests/dashbio_demos/dash-circos/app.py
Addresses this issue from Dash Sample Apps: https://github.com/plotly/dash-sample-apps/issues/362
The Circos plot would not be visible until the user clicked on the 'Table' tab. Once this tab was triggered, then the plot would show up no matter which tab was clicked on. The callback that was responsible for displaying the plot was blocked by the data table inside the 'Table' tab. 
Here is a very similar issue: https://github.com/plotly/dash/issues/1010 (Thank you to @michaelbabyn for showing me this).
In order to combat this, I created an empty datable just before dcc.Tabs was declared. Now this app functions as intended.
=> fix Circos plot bug, now shows plot immediately

dash_bio/component_factory/_clustergram.py, dash_bio/component_factory/_manhattan.py, dash_bio/component_factory/_volcano.py, requirements.txt
This PR proposes to bump the plotly.py dependency to the 4.x series, and modifies accordingly some components with the new syntax `graph_objects` instead of `graph_objs`. (4.0 was released in July 2019)
=> graph_objs --> graph_objects

.circleci/config.yml
This PR addresses the `dash-bio` component of plotly/dash-core#282, and adds authentication for Dockerhub requests for CI testing. The Circle CI `config.yml` is modified with the `dashAutomation` account details.
=> Adding dockerhub authentication

.circleci/config.yml, dash_bio/component_factory/_clustergram.py
This PR adds some minor fixes to the CI config in relation to the addition of the `orjson` dependency in `dash-2.0.0`.
=> Fixing CI config for Rust install in `dash`

dev-requirements.txt, src/lib/components/NeedlePlot.react.js, src/lib/fragments/NeedlePlot.react.js, tests/integration/test_needle_plot.py
Closes #545 
I am adding a feature to an existing component.
Create a new feature.
I added height and width properties to the NeedlePlot component and fragment.  In the NeedlePlot component, I add height and width properties as well set them.  In the NeedlePlot component, I gave the div and plot component these properties.
Also, I created tests for checking that these properties work as expected.
=> Add resizing plot feature and created tests for this feature.

src/lib/components/OncoPrint.react.js, tests/dashbio_demos/dash-onco-print/README.md
Change a description of the onco-print property range in OncoPrint.react.js and in README.md.
=> Fix onco-print range property description.

tests/dashbio_demos/common/requirements.txt, tests/dashbio_demos/dash-alignment-chart/requirements.txt, tests/dashbio_demos/dash-circos/requirements.txt, tests/dashbio_demos/dash-clustergram/requirements.txt, tests/dashbio_demos/dash-forna-container/requirements.txt, tests/dashbio_demos/dash-ideogram/requirements.txt, tests/dashbio_demos/dash-igv/requirements.txt, tests/dashbio_demos/dash-manhattan-plot/requirements.txt, tests/dashbio_demos/dash-molecule-2d-viewer/requirements.txt, tests/dashbio_demos/dash-molecule-3d-viewer/requirements.txt, tests/dashbio_demos/dash-needle-plot/requirements.txt, tests/dashbio_demos/dash-onco-print/requirements.txt, tests/dashbio_demos/dash-sequence-viewer/requirements.txt, tests/dashbio_demos/dash-speck/requirements.txt, tests/dashbio_demos/dash-variant-map/requirements.txt, tests/dashbio_demos/dash-volcano-plot/requirements.txt
`numpy` has an update that resulted in a million dependabot PRs. We can't accept those because newer `numpy` versions are restricted to Py3.8+ - but we can simply unpin it and folks will get the top version available for their Python version.
=> remove numpy pin in demos

dash_bio/component_factory/_manhattan.py, tests/integration/test_manhattan_plot.py
While using dash-bio to create an interactive Manhattan plot, I noticed it fails if there is only one chromosome in the chromosome column (CHR).
Here is the error message:
```
~/site-packages/dash_bio/component_factory/_manhattan.py:153: in ManhattanPlot
highlight_color=highlight_color
~/site-packages/dash_bio/component_factory/_manhattan.py:535: in figure
text=hover_text
~/site-packages/plotly/graph_objs/_scattergl.py:2778: in __init__
self["marker"] = _v
~/site-packages/plotly/basedatatypes.py:4828: in __setitem__
self._set_compound_prop(prop, value)
~/site-packages/plotly/basedatatypes.py:5239: in _set_compound_prop
val = validator.validate_coerce(val, skip_invalid=self._skip_invalid)
~/site-packages/_plotly_utils/basevalidators.py:2467: in validate_coerce
v = self.data_class(v, …
```
=> fix single chromosome bug + add small test

tests/dashbio_demos/dash-circos/app.py
Fixed a broken link (it had a redundant character at the end)
The change is for this demo app: https://dash.gallery/dash-circos/
=> fix broken link
